services:
  - type: web
    name: calibre-web
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: GOOGLE_DRIVE_ENABLED
        value: "true"
      - key: GOOGLE_DRIVE_CLIENT_ID
        sync: false
      - key: GOOGLE_DRIVE_CLIENT_SECRET
        sync: false
    disk:
      name: calibre-data
      mountPath: /data
      sizeGB: 1
